volumes:
  fine-whatevers-data:
    external: true
services:
  postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES= users, arts
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
  fw-service:
    build:
      context: ./fw-service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./fw-service:/app
    environment:
      DATABASE_URL: postgresql://user-name:password@postgres/db-name
      WAIT_HOSTS: postgres:5432
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: fw-servicepostgres
    ports:
      - "15432:5432"
    volumes:
      - fine-whatevers-data:/var/lib/postgresql/data

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
