volumes:
  fwvolume:
    external: true
services:
  fastapi:
    build:
      context: ./fw
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./fw:/app
    environment:
      DATABASE_URL: postgresql://user:user@db/fwpostgres
      WAIT_HOST: db:5432
  db:
    image: postgres:latest
    volumes:
    - fwvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fwpostgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 15432:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
